### PR TITLE
Update README.md with logo and Readme link

### PR DESCRIPTION
**Pull request by ritwik-g**
## What

- Changed the logo link to fix pypy package
- Fixed read me link at the end of doc

## Why

...

## How

...

## Relevant Docs

-

## Related Issues or PRs

-

## Dependencies Versions / Env Variables

-

## Notes on Testing

...

## Screenshots

...

## Checklist

I have read and understood the [Contribution Guidelines]().

### CODE REVIEW

**Review by chandrasekharan-zipstack — APPROVED** [review]
LGTM - you'll need to update the patch version in `__init__.py` to release this

**Comment by ritwik-g** [comment]
> LGTM - you'll need to update the patch version in `__init__.py` to release this

Should this be released just for a readme change? I think this can be rolled out in next release may be? @hari-kuriakose @chandrasekharan-zipstack

**Comment by hari-kuriakose** [comment]
> > LGTM - you'll need to update the patch version in `__init__.py` to release this
> 
> Should this be released just for a readme change? I think this can be rolled out in next release may be? @hari-kuriakose @chandrasekharan-zipstack

@ritwik-g @chandrasekharan-zipstack  Should be ok if README changes are directly picked up by PyPI. Let's see.

**Review by hari-kuriakose — APPROVED** [review]
@ritwik-g LGTM

**Comment by hari-kuriakose** [comment]
@ritwik-g @chandrasekharan-zipstack Seems like PyPI updates their CDN only when you publish. Hence if it's any critical README update, let's release it immediately. Otherwise should be ok to wait until next feature release.

**Pull request merged**
